name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build the Docker image
      run: make prepare

    - name: Build and release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
